version: '3.6'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGODB_USER: paul
      MONGODB_DATABASE: paulsshortener
      MONGODB_PASS: paulspw
    ports:
      - "12345:27017"
